---
- name: "[{{backup_type}} backup] Adding cronjob for backup script"
  cron: name="Periodic {{backup_type}} backup" hour="*/6" minute="0" job="{{backup_script}}" user={{backups_user}}

- name: "[{{backup_type}} backup] Creating backup script"
  template: src="backup-wrapper.sh" dest="{{backup_script}}"
            owner={{backups_user}} group={{backups_group}} mode=u+x

- name: Install backup check
  include_role:
    name: backup_check

  # {{backups_dir}}/{{backup_type}}