---
# Note: install homeassistant before roofcam, because homeassistant takes a long time to start up the first time
# This way, homeassistant can already start up while we install roofcam
- hosts: home
  roles:
    - { role: base, tags: ['base']}
    - { role: homeassistant, tags: ['homeassistant', 'hass']}
    - { role: hadashboard, tags: ['appdaemon', 'hadash', 'hadashboard'], appdaemon_venv: "{{homeassistant_venv}}"}
    - { role: roofcam, tags: ['roofcam']}
    - { role: node-sonos-http-api, tags: ['sonos']}
    - { role: monit, tags: ['monit']}

