---
#- debug: msg="{{item.name}} =  {{item.value | replace('\n', '')}}"
#  with_items:
#   - {name: nest_client_id, value: "{{nest_client_id}}"}
#   - {name: nest_client_secret, value: "{{nest_client_secret}}"}
#   - {name: nest_access_token, value: "{{nest_access_token}}"}
#   - {name: atv_login_id, value: "{{atv_login_id}}"}
#   - {name: phue_username, value: "{{phue_username}}"}
#   - {name: monit_http_password, value: "{{monit_http_password}}"}


- name: Creating custom check script directory
  become: yes
  file: path="{{monit_custom_checks_dir}}" state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}}

- name: Copying custom check scripts
  template: src={{item}} dest={{monit_custom_checks_dir}}/{{item}}
            owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=u+rwx
  notify:
    - reload_monit
  become: yes
  with_items:
    - mycheck.sh

- name: Installing monit
  apt: name={{item}} state=present
  become: yes
  with_items:
    - monit

- name: Configuring monit
  template: src=monitrc dest=/etc/monit/monitrc
  notify:
    - reload_monit
  become: yes

- name: Installing custom monit checks
  template: src=checks dest=/etc/monit/conf-enabled/checks
  notify:
    - reload_monit
  become: yes