---
- name: Installing monit
  apt: name={{item}} state=present
  become: yes
  with_items:
    - monit

- name: Configuring monit
  template: src=monitrc dest=/etc/monit/monitrc
  notify:
    - reload_monit
  become: yes

- name: Installing custom monit checks
  template: src=checks dest=/etc/monit/conf-enabled/checks
  notify:
    - reload_monit
  become: yes