---
- hosts: home
  tasks:
    - name: "Check that we have generated a valid api token before running this tool "
      pause:
        prompt: "Did you generate a new grafana_backups_api_token and set it in the inventory? [Enter to continue, CRTL-C to cancel]"

    - name: Cloning grafana-backup-tool from github
      git: repo=https://github.com/ysde/grafana-backup-tool.git dest="/tmp/grafana-backup-tool"
    # - name: "Copying latest grafana backup "

    - name: "Determining filename of latest grafana backup"
      shell: "ls /opt/networkshare/auto_backups/$(ls /opt/networkshare/auto_backups/ | tail -n 1)/grafana*"
      register: grafana_backup_path

    - debug:
        var: grafana_backup_path

    - name: "Copying latest grafana backup copy to /tmp"
      shell: "cp {{grafana_backup_path.stdout}} /tmp;"

    - name: "Extracting latest grafana backup copy to /tmp"
      unarchive:
        remote_src: yes
        src: "{{grafana_backup_path.stdout}}"
        dest: /tmp/
      become: yes

    - name: "Running backup-tool"
      shell: |
                export GRAFANA_URL="http://0.0.0.0:3001";
                export GRAFANA_TOKEN="{{grafana_backups_api_token}}";
                ls /tmp/dashboards/ | awk '{ print "python /tmp/grafana-backup-tool/createDashboard.py /tmp/dashboards/"$1}' | sh

# cd /tmp; git clone https://github.com/ysde/grafana-backup-tool.git
# # Get token from http://casa:3001/org/apikeys
# export GRAFANA_URL="http://casa:3001"; export GRAFANA_TOKEN="<token>";
# python grafana-backup-tool/createDashboard.py ~/Downloads/dashboards/Overview.dashboard