---
- name: Determining Node version
  shell: "node --version"
  register: node_version
  changed_when: False
  ignore_errors: yes

- name: Adding NodeJS 6 package source
  shell: "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
  become: yes
  when: node_version|failed

- name: Installing NodeJS
  apt: name={{item}} state=present
  become: yes
  with_items:
    - nodejs  # npm is included

- name: Creating node-sonos-http-api directory
  file: path="{{sonos_http_api_dir}}" state=directory owner="{{sonos_http_api_user}}" group="{{sonos_http_api_group}}"
  become: yes

- name: Cloning node-sonos-http-api from github
  git: repo="{{sonos_http_api_repo}}" dest="{{sonos_http_api_dir}}"
  register: node_sonos_http_api_git

- name: Installing node-sonos-http-api
  shell: "npm install --production"
  args:
    chdir: "{{sonos_http_api_dir}}"
  when: node_sonos_http_api_git.changed

- name: Adding presets
  template: src=presets/{{item.src}} dest="{{sonos_http_api_dir}}/presets/{{item.dest}}"
  with_items:
    - { src: "downstairs.json", dest: "breakfast.json", favorite: "'t Koffiehuis" }
    - { src: "downstairs.json", dest: "party.json", favorite: "Throwback Party" }
    - { src: "downstairs.json", dest: "pop.json", favorite: "Today's Top Hits" }
    - { src: "downstairs.json", dest: "lounge.json", favorite: "Lounge - Soft House" }
    - { src: "downstairs.json", dest: "romance.json", favorite: "Jazzy Romance" }
    - { src: "downstairs.json", dest: "christmas.json", favorite: "Christmas Is Coming" }
    - { src: "downstairs.json", dest: "coffee_bar.json", favorite: "Your Favorite Coffeehouse" }
    - { src: "downstairs.json", dest: "relaxing.json", favorite: "Relax & Unwind" }
    - { src: "downstairs.json", dest: "disney.json", favorite: "Disney Greatest Hits" }
    - { src: "downstairs.json", dest: "dinner_with_friends.json", favorite: "Dinner with Friends" }
    - { src: "nomusic.json", dest: "nomusic.json", players: ["TV Room", "Living Room"] }
    - { src: "upstairs.json", dest: "bathroom_morning.json", favorite: "Morning Motivation" }
    - { src: "upstairs.json", dest: "bathroom_relaxing.json", favorite: "Relax & Unwind" }
    - { src: "nomusic.json", dest: "bathroom_nomusic.json", players: ["Bathroom"] }
  notify:
    - restart_sonos_http_api

- name: Installing sonos-http-api systemd service
  template: src=node-sonos-http-api.service dest=/etc/systemd/system/{{sonos_http_api_service}}.service
  notify:
    - daemon_reload
    - restart_sonos_http_api
  become: yes

- name: "Add iptable rule for node-sonos-http-api"
  iptables: chain=INPUT protocol=tcp destination_port={{sonos_http_api_port}} source={{casa_subnet}} ctstate=NEW,ESTABLISHED jump=ACCEPT
            comment="node-sonos-http-api"
  become: yes
  notify: save_iptables
  tags: [iptables, iptable]

- name: Installing some convenience aliases
  template: src=node-sonos-http-api-aliases.sh dest=/etc/profile.d/node-sonos-http-api-aliases.sh
  become: yes

- name: Make sure sonos-http-api service is started
  service: name={{sonos_http_api_service}} state=started enabled=yes
  become: yes
