---
- name: Creating node_exporter casa-service
  include_role:
    name: casa-service
  vars:
    service_name: "node_exporter"
  become: yes

- name: "Installing prometheus-node-exporter"
  shell: >
    curl -L  {{node_exporter_download_url}} -o node_exporter.tar.gz;
    tar xvf node_exporter.tar.gz;
    cp node_exporter*/node_exporter {{node_exporter_dir}}/node_exporter
  args:
    chdir: "/tmp"
    creates: "{{node_exporter_dir}}/node_exporter"
  become: yes

- name: Installing prometheus-node-exporter systemd service
  template: src=prometheus-node-exporter.service dest=/etc/systemd/system/{{node_exporter_service}}.service
  notify:
    - daemon_reload
    - restart_node_exporter
  become: yes

- name: Creating textfile exports directory
  file: dest={{node_exporter_textfile_exports}} state=directory owner={{node_exporter_user}} group={{node_exporter_group}} mode=o+w
  become: yes

# NOTE: Don't expose node-exporter IPs, that data can be accessed through prometheus
# - name: "Add iptable rule for node-exporter"
#   iptables: chain=INPUT protocol=tcp destination_port={{node_exporter_port}} source={{casa_subnet}} ctstate=NEW,ESTABLISHED jump=ACCEPT
#             comment="Prometheus Node Exporter"
#   become: yes
#   notify: save_iptables
#   tags: [iptables, iptable]