################################################################################
# Office                                                                       #
################################################################################

- name: OfficeEvening
  entities:
    light.office:
        state: on
        kelvin: 2000
        brightness_pct: 75