---
- name: "Installing prometheus-node-exporter"
  shell: >
    curl -L  https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz | tar zxv;
    cp node_exporter-0.16.0.linux-amd64/node_exporter {{prometheus_dir}}/node_exporter
  args:
    chdir: "/tmp"
    creates: "{{prometheus_dir}}/node_exporter"
  become: yes

- name: Installing prometheus-node-exporter systemd service
  template: src=prometheus-node-exporter.service dest=/etc/systemd/system/{{node_exporter_service}}.service
  notify:
    - daemon_reload
    - restart_node_exporter
  become: yes

- name: Creating textfile exports directory
  file: dest={{node_exporter_textfile_exports}} state=directory owner={{prometheus_user}} group={{prometheus_group}} mode=o+w
  become: yes

# NOTE: Don't expose node-exporter IPs, that data can be accessed through prometheus
# - name: "Add iptable rule for node-exporter"
#   iptables: chain=INPUT protocol=tcp destination_port={{node_exporter_port}} source={{casa_subnet}} ctstate=NEW,ESTABLISHED jump=ACCEPT
#             comment="Prometheus Node Exporter"
#   become: yes
#   notify: save_iptables
#   tags: [iptables, iptable]