---
- name: Only run "apt update_cache=yes" if we last did so more than 3600 seconds ago
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: "Installing some convenience utilities (system)"
  apt: name={{item}} state=present
  become: yes
  with_items:
    - gcc
    - git
    - python-setuptools # Installs easy_install
    - python-virtualenv
    - vim
    - silversearcher-ag
    - logrotate
    - net-tools # ifconfig
    - tree
    - grc # generic colourizer https://github.com/garabik/grc

- name: "Installing pip"
  easy_install: name=pip
  become: yes

- name: "Installing more utilities (python)"
  pip: name={{item}} state=present
  with_items:
    - httpie
  become: yes

- name: "Enabling line numbers in vim"
  lineinfile:
    dest: /etc/vim/vimrc
    line: "set number"
  become: yes