---
- name: Add authorized key for casa
  authorized_key: user={{ansible_ssh_user}} key="{{casa_public_key}}"

- name: Install custom sshd_config file
  template: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart_sshd
  become:  yes

- name: Only run "apt update_cache=yes" if we last did so more than 3600 seconds ago
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: "Installing some convenience utilities (system)"
  apt: name={{item}} state=present
  become: yes
  with_items:
    - gcc
    - git
    - python-setuptools # Installs easy_install
    - python-virtualenv
    - vim
    - silversearcher-ag
    - logrotate
    - net-tools # ifconfig
    - sysstat # mpstat
    - tree
    - grc # generic colourizer https://github.com/garabik/grc
    - jq
    - libxml2-dev
    - libxslt1-dev

- name: "Installing pip"
  easy_install: name=pip
  become: yes

- name: "Installing rg"
  shell: >
    curl -L  https://github.com/BurntSushi/ripgrep/releases/download/0.7.1/ripgrep-0.7.1-x86_64-unknown-linux-musl.tar.gz | tar zxv;
    cp ripgrep-0.7.1-x86_64-unknown-linux-musl/rg /usr/bin/rg
  args:
    chdir: "/tmp"
    creates: "/usr/bin/rg"
  become: yes

- name: "Installing more utilities (python)"
  pip: name={{item}} state=present
  with_items:
    - httpie
  become: yes

- name: "Enabling line numbers in vim"
  lineinfile:
    dest: /etc/vim/vimrc
    line: "set number"
  become: yes

# Needed in order to use a MBP as server
- name: "Making sure the server doesn't suspend on lid close"
  lineinfile:
    dest: /etc/systemd/logind.conf
    line: "HandleLidSwitch=ignore"
  notify: restart_logind
  become: yes

- name: Installing bash profile
  template: src=casa_profile.sh dest=/etc/profile.d/casa_profile.sh
  become: yes

- name: Creating tools directory
  file: dest={{tools_dir}} state=directory owner={{tools_user}} group={{tools_group}}
  become: yes

- name: Copying files to {{tools_dir}}
  copy:
    src: simple-server.py
    dest: "{{tools_dir}}/simple-server.py"

- name: "Installing basic IP Tables rules"
  include_tasks: install_iptable_rules.yml
  become: yes
  tags:
    - iptables
    - iptable