sensu_conf_dir: /etc/sensu/conf.d
sensu_installation_dir: "/opt/sensu"
sensu_custom_handlers_dir: "{{sensu_installation_dir}}/handlers"
sensu_user: "sensu"
sensu_group: "sensu"

sensu_api_port: 4567
sensu_api_host: "{{ansible_hostname}}" # This needs to be a resolvable hostname
sensu_api_bind: "0.0.0.0"
sensu_api_user: "api-user"
sensu_api_password: "password"

sensu_default_check_interval: 5
sensu_default_refresh_interval: "{{sensu_default_check_interval * 3}}"

redis_host: "127.0.0.1"
redis_port: 6379
redis_password: "secret"
redis_conf_dir: /etc/redis
redis_user: redis
redis_group: "{{redis_user}}"

uchiwa_host: "0.0.0.0"
uchiwa_port: 3000
uchiwa_conf_dir: /etc/sensu
uchiwa_user: "uchiwa-user"
uchiwa_password: "password"