sensu_conf_dir: /etc/sensu/conf.d
sensu_user: "{{ansible_ssh_user}}"
sensu_group: "{{sensu_user}}"
sensu_api_port: 4567
sensu_api_host: "casa"
sensu_api_bind: "0.0.0.0"

redis_host: "127.0.0.1"
redis_port: 6379
redis_password: "secret"
redis_conf_dir: /etc/redis
redis_user: redis
redis_group: "{{redis_user}}"

uchiwa_host: "0.0.0.0"
uchiwa_port: 3000
uchiwa_conf_dir: /etc/sensu