# For automations to work from both manual triggers a
# We need both scene (=manual scene setting) and homeassistant (=HADashboard API call) triggers for this
- id: weekend_breakfast_music
  alias: 'Play Weekend Breakfast Music'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.weekend_breakfast
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.weekend_breakfast
        domain: scene
        service: turn_on
  action:
    service: shell_command.play_sonos_favorite
    data:
      favorite: "'t%20Koffiehuis"
      room: "Living%20Room"

- id: enable_all_cameras
  alias: 'Enable all cameras'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.leave
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.leave
        domain: scene
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.slaapwel
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.slaapwel
        domain: scene
        service: turn_on
  action:
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.diepvries}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.hallway}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.front_garden}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.back_garden}}"

- id: disable_diepvries_cam
  alias: 'Disable diepvries cam, enabling all others'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.coming_home
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.coming_home
        domain: scene
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.good_morning
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.good_morning
        domain: scene
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.start_work_day
        domain: homeassistant
        service: turn_on
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: scene.start_work_day
        domain: scene
        service: turn_on
  action:
    - service: shell_command.disable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.diepvries}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.hallway}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.front_garden}}"
    - service: shell_command.enable_nest_camera
      data:
        camera_serial_id: "{{nest_cam_serial_ids.back_garden}}"