homeassistant:
{% for key, value in homeassistant_general_config.iteritems() %}
  {{key}}: {{value}}
{% endfor %}

# Discover some devices automatically
# discovery:

logger:
  default: info

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  - platform: nmap_tracker
    hosts: {{nmap_tracker_hosts}}
    track_new_devices: no

# Track the sun
sun:

# Enable iOS support
ios:

scene:
    - name: Slaapwel
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: TV Kijken
      entities:
        light.woonkamer_tv:
            state: on
            brightness: 143
        light.living_room:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: TV Lezen
      entities:
        light.woonkamer_tv:
            state: on
            brightness: 255
        light.living_room:
            state: off
        light.kitchen:
            state: off

    - name: Koken
      entities:
        light.woonkamer_tv:
            state: off
        light.living_room:
            state: on
            brightness: 143
        light.kitchen:
            state: on

    - name: Leave
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: Weekend Breakfast
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: on
        light.kitchen:
            state: off
        media_player.living_room:
            state: playing
            source: "'t Koffiehuis"


          #      media_player.living_room:
#          state: paused

#{"entity_id": "media_player.tv_room", "source": "'t Koffiehuis"}



media_player:
  - platform: sonos
  - platform: cast # Chromecast
  - platform: samsungtv
    host: {{samsungtv_host}}
  # Apparently Hass' spotify component doesn't recognize sonos devices :(
  # https://community.home-assistant.io/t/spotify-does-not-find-sonos-players-in-source/16245
  - platform: spotify
    client_id: {{spotify_client_id}}
    client_secret: {{spotify_client_secret}}

apple_tv:
  - name: Apple TV
    host: {{atv_host}}
    login_id: {{atv_login_id}}
    start_off: false
#    credentials: CREDENTIALS


light:
  platform: hue
  host: {{phue_ip}}

panel_iframe:
  roofcam:
    title: 'roofcam'
    url: 'http://{{roofcam_ip}}:{{roofcam_port}}'
    icon: 'mdi:camcorder'

sensor:
    - platform: systemmonitor
      resources:
         - type: memory_free
         - type: disk_use_percent
           arg: /
         - type: memory_use_percent
    - platform: fastdotcom
      minute:
         - 1
         - 21
         - 41
    - platform: buienradar
      monitored_conditions:
        - symbol
        - humidity
        - temperature
        - windspeed
        - pressure
    - platform: google_travel_time
      api_key: {{google_travel_time_api_key}}
      origin: {{google_travel_time_origin}}
      destination: {{google_travel_time_destination}}
      name: {{google_travel_time_name}}


nest:
    client_id: {{nest_client_id}}
    client_secret: {{nest_client_secret}}


######################
##  CONFIG EDITOR   ##
#####################

# Enable config editor
config:

group: !include groups.yaml

#zwave:
#  device_config: !include zwave_device_config.yaml


###################
##  AUTOMATION   ##
##################

# Include the automation editor:
automation: !include automations.yaml


#automation:
#- alias: Turn on kitchen light when there is movement
#  trigger:
#    platform: state
#    entity_id: binary_sensor.hallway_camera_motion_detected
#    to: 'on'
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.hall

#- alias: Turn off kitchen light 10 minutes after last movement
#  trigger:
#    platform: state
#    entity_id: binary_sensor.hallway_camera_motion_detected
#    to: 'off'
#    for:
#      seconds: 10
#  action:
#    service: homeassistant.turn_off
#    entity_id: light.hall
