homeassistant:
{% for key, value in homeassistant_general_config.iteritems() %}
  {{key}}: {{value}}
{% endfor %}

# Discover some devices automatically
# discovery:

# Set API Password
http:
  api_password: {{homeassistant_http.api_password}}
  trusted_networks:
{% for network in homeassistant_http.trusted_networks %}
     - {{network}}
{% endfor %}
    
logger:
  default: info

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  - platform: nmap_tracker
    hosts: {{nmap_tracker_hosts}}
    track_new_devices: no

# Track the sun
sun:

# Enable iOS support
ios:


weblink:
  entities:
    - name: Sonos HTTP API
      url: http://localhost:{{sonos_http_api_port}}/
    - name: HADashboard
      url: {{appdaemon_dash_url}}
    - name: Monit Dashboard
      url: http://localhost:{{monit_http_port}}

scene:
    - name: Slaapwel
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: Leave
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: TV Kijken
      entities:
        light.woonkamer_tv:
            state: on
            brightness: 143
        light.living_room:
            state: off
        light.kitchen:
            state: off
        media_player.living_room:
            state: paused

    - name: TV Lezen
      entities:
        light.woonkamer_tv:
            state: on
            brightness: 255
        light.living_room:
            state: off
        light.kitchen:
            state: off

    - name: Koken
      entities:
        light.woonkamer_tv:
            state: off
        light.living_room:
            state: on
            brightness: 143
        light.kitchen:
            state: on

    - name: Weekend Breakfast
      entities:
        light.woonkamer_tv:
            state: off
        light.garden:
            state: off
        light.living_room:
            state: off
        light.eettafel:
            state: on
        light.kitchen:
            state: off

    - name: Good Morning
      entities:
        light.garden:
            state: off

    # 'Coming Home' really just needs to turn off the diepvries cam which happens through an automation
    # However, HomeAssistant doesn't like empty entity dicts in scenes
    - name: Coming Home
      entities:
        light.eettafel:
            state: off

    - name: Start Work Day
      entities:
        light.garden:
            state: off

media_player:
  - platform: sonos
  - platform: cast # Chromecast
  - platform: samsungtv
    host: {{samsungtv_host}}
  # Apparently Hass' spotify component doesn't recognize sonos devices :(
  # https://community.home-assistant.io/t/spotify-does-not-find-sonos-players-in-source/16245
  - platform: spotify
    client_id: {{spotify_client_id}}
    client_secret: {{spotify_client_secret}}

# There's issues with AppleTV that cause the TV to turn on randomly. Disabling it for now.
# - https://community.home-assistant.io/t/apple-tv-apple-tv-failed-to-login/11694/53
# - https://github.com/home-assistant/home-assistant/issues/6777
# apple_tv:
#   - name: Apple TV
#     host: {{atv_host}}
#     login_id: {{atv_login_id}}
#     start_off: false
#    credentials: CREDENTIALS


light:
  platform: hue
  host: {{phue_ip}}

panel_iframe:
  roofcam:
    title: 'roofcam'
    url: 'http://{{roofcam_ip}}:{{roofcam_port}}'
    icon: 'mdi:camcorder'

sensor:
    - platform: systemmonitor
      resources:
         - type: memory_free
         - type: disk_use_percent
           arg: /
         - type: memory_use_percent
    - platform: fastdotcom
      minute:
         - 1
         - 21
         - 41
    - platform: buienradar
      monitored_conditions:
        - symbol
        - humidity
        - temperature
        - windspeed
        - pressure
    - platform: google_travel_time
      api_key: {{google_travel_time_api_key}}
      origin: {{google_travel_time_origin}}
      destination: {{google_travel_time_destination}}
      name: {{google_travel_time_name}}


nest:
    client_id: {{nest_client_id}}
    client_secret: {{nest_client_secret}}

{#
  1. Use %raw to insert braces into the lines below without ansible replacing them.
  2. FYI that in shell_command can't combine variables with actual shells (so using >> and | won't work)
     This is to ensure we're not just executing arbitrary shell commands based on user input.
     See https://github.com/home-assistant/home-assistant/blob/3ee4d1060fdbe067c19f7d4ce4777a7eb9dbb412/
     homeassistant/components/shell_command.py#L59-L65
#}
shell_command:
    play_sonos_favorite: 'curl "{{sonos_http_api_url_base}}/{% raw %}{{room}}/favorite/{{favorite}}{% endraw %}"'
    enable_nest_camera: '{{homeassistant_venv}}/bin/nest --client-id {{nest_client_id}} --client-secret {{nest_client_secret}} --token-cache {{homeassistant_dir}}/nest.conf --serial {% raw %}{{camera_serial_id}}{% endraw %} camera-streaming --enable-camera-streaming'
    disable_nest_camera: '{{homeassistant_venv}}/bin/nest --client-id {{nest_client_id}} --client-secret {{nest_client_secret}} --token-cache {{homeassistant_dir}}/nest.conf --serial {% raw %}{{camera_serial_id}}{% endraw %} camera-streaming --disable-camera-streaming'


######################
##  CONFIG EDITOR   ##
#####################

# Enable config editor
config:

group: !include groups.yaml

#zwave:
#  device_config: !include zwave_device_config.yaml


###################
##  AUTOMATION   ##
##################

# Include the automation editor:
automation: !include automations.yaml

