#########################################################################
# Grouping of light sources                                             #
#########################################################################

lights_downstairs:
  name: "Downstairs lights"
  view: no
  entities:
   - light.woonkamer_tv
   - light.tv_staanlamp
   - light.living_room
   - light.dining_table
   - light.kitchen
   - light.office
   - switch.desk_lamp

lights_downstairs_automatic:
  name: "Automatically controlled downstairs lights"
  view: no
  entities:
    - light.office_ambience

lights_outside:
  name: "Lights outside"
  view: no
  entities:
    - light.voordeur
    - light.garden