#####################################################
# House Scenes                                      #
#####################################################
- name: Sleeping
  entities:
    group.lights_outside:
        state: off
    group.lights_downstairs:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_boolean.cooking:
        option: off
    input_select.camera_preset:
        option: All On

- name: Home
  entities:
    input_select.camera_preset:
        option: Home

- name: Away
  entities:
    group.lights_outside:
        state: off
    group.lights_downstairs:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.bathroom_music:
        option: Bathroom NoMusic
    input_boolean.cooking:
        option: off
    input_select.camera_preset:
        option: All On

###################################
# Living scenes                  #
###################################

- name: Watching TV
  entities:
    light.woonkamer_tv:
        state: on
        kelvin: 2200
        brightness_pct: 40
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: NoMusic
    input_select.camera_preset:
        option: Home

- name: Breakfast
  entities:
    light.woonkamer_tv:
        state: off
    light.tv_staanlamp:
        state: off
    light.garden:
        state: off
    light.living_room:
        state: off
    light.eetkamer:
        state: on
    light.kitchen:
        state: off
    light.kantoor:
        state: off
    input_select.downstairs_music:
        option: Breakfast
    input_select.camera_preset:
        option: Home

- name: Romance
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.kantoor:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Romance
    input_select.camera_preset:
        option: Home

- name: Christmas
  entities:
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Christmas
    input_select.camera_preset:
        option: Home

- name: Relaxing
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 143
    light.tv_staanlamp:
        state: on
        kelvin: 2200
        brightness_pct: 20
    light.kantoor:
        state: off
    light.living_room:
        state: off
    input_select.downstairs_music:
        option: Relaxing
    input_select.camera_preset:
        option: Home

- name: Reading
  entities:
    light.woonkamer_tv:
        state: on
        brightness: 255
    light.living_room:
        state: off
    light.kitchen:
        state: off
    input_select.camera_preset:
        option: Home

- name: NoPreset
  entities:
    media_player.living_room:
        state: paused
    media_player.tv_room:
        state: paused

- name: Sunset
  entities:
    group.lights_outside:
        state: on
    light.kantoor_sfeer_lamp_1:
        state: on
        kelvin: 2200
        brightness_pct: 20
        # Apparently brightness_pct doesn't work on a light group, hence why this is kantoor_sfeer_lamp_1
        # and not kantoor_sfeer_verlichting

- name: Midnight
  entities:
    group.lights_outside:
        state: off

##################
# Cooking        #
##################

- name: Cooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: on
    input_select.camera_preset:
        option: Home

- name: StopCooking
  entities:
    light.living_room:
        state: off
    light.kitchen:
        state: off

############
# Mornings #
############
- name: StartWorkDay
  entities:
    group.lights_outside:
        state: off
    light.kantoor:
        state: on
    light.nachttafel_joris:
        state: off
    light.kitchen:
        state: on
    input_select.bathroom_music:
        option: NoMusic
    input_select.downstairs_music:
        option: Pop
    switch.desk_lamp:
        state: on
    input_select.camera_preset:
        option: Home

- name: BathroomMorningWeekDay
  entities:
    input_select.bathroom_music:
        option: Bathroom Morning
