restart_homeassistant:
  sequence:
    - service: homeassistant.restart
restart_sonos:
  sequence:
    - service: shell_command.restart_sonos
turn_off_tv:
  sequence:
    - service: shell_command.samsungtv_send_key
      data:
        key: "KEY_POWEROFF"
