---
- name: "Installing homeassistant system dependencies"
  apt: name={{item}} state=present
  become: yes
  with_items:
    - python3-dev
    - nmap
    - libffi-dev # Required by pyatv
    - libssl-dev # Required by pyatv

- name: Creating homeassistant directory
  file: path={{homeassistant_dir}} state=directory owner={{ansible_ssh_user}}
  become: yes

- name: Manually create the initial virtualenv
  command: virtualenv {{homeassistant_venv}} -p python3 creates="{{homeassistant_venv}}"

- name: "Installing homeassistant"
  pip: name=homeassistant virtualenv="{{homeassistant_venv}}" version=0.53.0

- name: "Installing pyatv"
  pip: name=pyatv virtualenv="{{homeassistant_venv}}"

- name: "Configuring homeassistant"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
   - configuration.yaml
   - automations.yaml
   - groups.yaml
   - known_devices.yaml
#   - nest.conf # Nest token needs to be refreshed every so often, installing an invalid one messes up HA
   - phue.conf
  notify:
    - restart_homeassistant

- name: Installing homeassistant systemd service
  template: src=homeassistant.service dest=/etc/systemd/system/homeassistant@{{ansible_ssh_user}}.service
  notify:
    - daemon_reload
    - restart_homeassistant
  become: yes

- name: Installing some convenience aliases
  template: src=hass-aliases.sh dest=/etc/profile.d/hass-aliases.sh
  become: yes

- name: Make sure homeassistant service is started
  service: name=homeassistant@{{ansible_ssh_user}} state=started enabled=yes
  become: yes