---
- name: Creating homeassistant group
  group: name="{{homeassistant_group}}" state=present system=yes
  become: yes

- name: Creating homeassistant user
  user: name="{{homeassistant_user}}" comment="Homeassistant User" group="{{homeassistant_group}}"
        home={{homeassistant_dir}} createhome=no system=yes # Not a login user
  become: yes

- name: Creating homeassistant directory
  file: path={{homeassistant_dir}} state=directory owner={{homeassistant_user}} group={{homeassistant_group}}
  become: yes

- name: "Configuring homeassistant automations"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
   - automations.yaml
  notify:
    - reload_homeassistant_automations
    # - restart_homeassistant
  tags:
    - hass-config
    - hass-automations
  become: yes

- name: "Configuring homeassistant known_devices (no restart needed)"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
    - known_devices.yaml
  tags:
    - hass-config
  become: yes

- name: "Configuring homeassistant"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
   - configuration.yaml
   - groups.yaml
   - scenes.yaml
   - scripts.yaml
#   - nest.conf # Nest token needs to be refreshed every so often, installing an invalid one messes up HA
   - phue.conf # No longer neccessary?
  notify:
    - reload_homeassistant_config
    # - restart_homeassistant
  tags:
    - hass-config
  become: yes

- name: "Adding prom2hass.sh script"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}} mode=u+x
  with_items:
   - prom2hass.py
  become: yes

- name: "Ensure all files are owned by the homeassistant user"
  file: path={{homeassistant_dir}} state=directory owner={{homeassistant_user}} group={{homeassistant_group}} recurse=yes
  become: yes

- name: Starting homeassistant docker container
  docker_container:
    name: "{{homeassistant_container_name}}"
    image: "{{homeassistant_docker_image}}"
    state: started # Modify and restart iff config has changed
    volumes:
      - "{{homeassistant_dir}}/:/config"
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    recreate: "{{recreate_containers}}"
    restart_policy: unless-stopped
  become: yes
  tags:
    - homeassistant-container

- name: "Docker post-startup changes"
  shell: "docker exec homeassistant {{item}}"
  with_items:
    - apt-get update
    - apt-get install -y jq
    - wget https://github.com/McKael/samtv/releases/download/v1.0.0/samtvcli-1.0.0-linux-amd64.tar.bz2 -O /tmp/samtvcli.tar.bz2
    - tar xvf /tmp/samtvcli.tar.bz2 -C /tmp
    - cp /tmp/1.0.0/linux-amd64/samtvcli /usr/bin/samtvcli
  become: yes

- name: Install casa-container for homeassistant (aliases only for now)
  include_role:
    name: casa-container
  vars:
    alias_shorthand: "ha"
    container_name: "{{homeassistant_container_name}}"

- name: "Add iptable rule for Homeassistant"
  iptables: chain=INPUT protocol=tcp destination_port={{homeassistant_port}} source={{casa_subnet}} ctstate=NEW,ESTABLISHED jump=ACCEPT
            comment=Homeassistant
  become: yes
  notify: save_iptables
  tags: [iptables, iptable]
