---
- name: "Installing homeassistant system dependencies"
  apt: name={{item}} state=present
  become: yes
  with_items:
    - python3-dev
    - nmap
    - libffi-dev # Required by pyatv
    - libssl-dev # Required by pyatv

- name: Creating homeassistant directory
  file: path={{homeassistant_dir}} state=directory owner={{homeassistant_user}} group={{homeassistant_group}}
  become: yes

- name: Manually create the initial virtualenv
  command: virtualenv {{homeassistant_venv}} -p python3 creates="{{homeassistant_venv}}"

- name: "Installing homeassistant"
  pip: name=homeassistant virtualenv="{{homeassistant_venv}}" version={{homeassistant_version}}
  notify:
    - restart_homeassistant

# During upgrade, homeassistant runs its own pip install processes
# ubuntu   15885 15869 42 15:01 ?        00:00:02 /opt/homeassistant/.venv/bin/python3 -m pip install
# --quiet sqlalchemy==1.1.14 --upgrade
# --constraint /opt/homeassistant/.venv/lib/python3.5/site-packages/homeassistant/package_constraints.txt

- name: "Installing pyatv"
  pip: name=pyatv virtualenv="{{homeassistant_venv}}"

- name: "Configuring homeassistant"
  template: src={{item}} dest={{homeassistant_dir}}/{{item}}
  with_items:
   - configuration.yaml
   - automations.yaml
   - groups.yaml
   - known_devices.yaml
#   - nest.conf # Nest token needs to be refreshed every so often, installing an invalid one messes up HA
   - phue.conf
  notify:
    - reload_homeassistant_config

- name: Installing homeassistant systemd service
  template: src=homeassistant.service dest=/etc/systemd/system/homeassistant@{{homeassistant_user}}.service
  notify:
    - daemon_reload
    - restart_homeassistant
  become: yes

- name: Installing some convenience aliases
  template: src=hass-aliases.sh dest=/etc/profile.d/hass-aliases.sh
  become: yes

- name: Make sure homeassistant service is started
  service: name=homeassistant@{{homeassistant_user}} state=started enabled=yes
  become: yes

