---
# This file contains a number of custom patches to work around bugs and issues
### NEST ###############################################################################################################

# Using a custom version of python-nest, let's install it from github
- name: "Installing patched python-nest"
  pip:
    name: "git+https://github.com/jorisroovers/python-nest.git@master#egg=python-nest"
    virtualenv: "{{homeassistant_venv}}"
  notify:
    - restart_homeassistant
  tags:
    - patch-nest

# On startup, home-assistant will install all packages in the REQUIREMENTS list of each component
# Details here: https://home-assistant.io/developers/component_deps_and_reqs/
# We need to avoid this from happening, so let's comment out the REQUIREMENTS line in HA's nest.py file
- name: "Patching home-assistant's nest.py component"
  lineinfile:
    dest: "{{homeassistant_venv}}/lib/python3.6/site-packages/homeassistant/components/nest.py"
    regexp: '(^REQUIREMENTS.*)'
    line: '# \1'
    backrefs: yes
  notify:
    - restart_homeassistant
  tags:
    - patch-nest

### TP-LINK ############################################################################################################

# New TP Link firmware breaks Home-assistant:
# https://community.home-assistant.io/t/tplink-hs110-smart-plug-configuration-help-error/31137/8
# https://github.com/GadgetReactor/pyHS100/issues/103
# https://github.com/GadgetReactor/pyHS100/pull/107

- name: "Installing patched pyHS100"
  pip:
    name: "git+https://github.com/rytilahti/pyHS100@281f2362217433523b17e98b63a9e2692eead50d#egg=pyHS100"
    virtualenv: "{{homeassistant_venv}}"
  notify:
    - restart_homeassistant
  tags:
    - patch-tplink

# We also need to make some local modifications to
# https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/tplink.py

- name: "Patching home-assistant's tplink component"
  copy:
    src: patches/tplink.py
    dest: "{{homeassistant_venv}}/lib/python3.6/site-packages/homeassistant/components/switch/tplink.py"
  notify:
    - restart_homeassistant
  tags:
    - patch-tplink