################################################################################
# From https://www.home-assistant.io/docs/automation/
# You need to set ' initial_state: True'
# If you don’t set this the previous state is restored.
# If you shut Home Assistant down before it finishes starting, the automation will be stored as being off,
# and your automations will be disabled at the next startup.
#
################################################################################
# Living Preset                                                                #
################################################################################

- alias: Automatically set scene for Living Preset
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.living_preset
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "{% raw %}scene.{{ states('input_select.living_preset') | lower | replace(' ', '_')}}{% endraw %}"

    # When disabling music, keep the current house mode (as this automation might be triggered by a change in
    # house mode). When enabling music, set house mode to Auto.
    - service: input_select.select_option
      data_template:
        entity_id: input_select.house_mode
        option: |
          {% raw %}
          {% if is_state('input_select.living_preset', 'NoPreset') %}
            {{ states('input_select.house_mode') }}
          {% else %}
            Auto
          {% endif %}
          {% endraw %}

################################################################################
# Music input to sonos preset                                                  #
################################################################################

- alias: Play downstairs sonos preset for music input select
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.downstairs_music
  action:
    - service: shell_command.play_sonos_preset
      data_template:
        preset: "{% raw %}{{ states('input_select.downstairs_music') | lower | replace(' ', '_')}}{% endraw %}"

################################################################################
# TV                                                                           #
################################################################################
- alias: Automatically set LivingPreset to Watching TV when turning on the TV
  initial_state: True
  trigger:
    platform: state
    entity_id: device_tracker.samsungtv
    to: "home"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.living_preset
        option: "Watching TV"

- alias: Automatically set LivingPreset to StopWatchingTV when turning off the TV before sunset
  initial_state: True
  trigger:
    platform: state
    entity_id: device_tracker.samsungtv
    to: "not_home"
  condition:
   - condition: and
     conditions:
       - condition: sun
         before: sunset
       - condition: sun         # This ensures the lights don't turn off post-midnight when turning off the TV
         before: sunrise
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.StopWatchingTV"

- alias: Turn off TV on away/sleep
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: "Away"
    - platform: state
      entity_id: input_select.house_mode
      to: "Sleeping"
  action:
    - service: shell_command.samsungtv_send_key
      data_template:
        key: "KEY_POWEROFF"

################################################################################
# Mornings                                                                     #
################################################################################

- alias: Start week day when exiting bathroom
  initial_state: True
  trigger:
    - platform: state
      entity_id: media_player.bathroom
      from: "playing"
      to: "paused"
    - platform: state
      entity_id: light.bathroom_group
      to: "off"
  condition:
   - condition: and
     conditions:
      - condition: time
        after: '07:00:00'
        before: '11:30:00'
      - condition: state
        entity_id: "binary_sensor.workday_sensor"
        state: "on"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.StartWeekDay"

- alias: Trigger BathroomMorning scene on light turn on during week days
  initial_state: True
  trigger:
    platform: state
    entity_id: light.nachttafel_joris
    to: "on"
  condition:
   - condition: and
     conditions:
      - condition: time
        after: '07:30:00'
        before: '11:30:00'
      - condition: state
        entity_id: "binary_sensor.workday_sensor"
        state: "on"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.BathroomMorningWeekDay"

- alias: Start work day turning on computer in the morning
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.joris_working
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: time
          after: '07:30:00'
          before: '11:30:00'
        - condition: state
          entity_id: "binary_sensor.workday_sensor"
          state: "on"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.StartWorkingMorning"

################################################################################
# Send message on nest-presence set to home or away                            #
################################################################################

- id: auto_away_nest_presence
  alias: 'Send message when away from home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.home_away
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Away
    - service: notify.slack
      data:
        message: |
              [Nest] You're gone from home! Set home automatically to away.

- id: auto_home_nest_presence
  alias: 'Send message when coming home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.home_away
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Auto
    - service: notify.slack
      data:
        message: |
              [Nest] Welcome home! Set home automatically to home.


################################################################################
# Sunrise/sunset                                                               #
################################################################################

- id: sunset_outdoor_lighting
  alias: 'Turning off outdoor lighting at midnight'
  initial_state: True
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.Midnight
    # Send slack notification when day, evening or away (not when sleeping).
    # Note that hass doesn't support 'not' conditions
    - condition: or
      conditions:
        - condition: state
          entity_id: "input_select.house_mode"
          state: "Day"
        - condition: state
          entity_id: "input_select.house_mode"
          state: "Evening"
        - condition: state
          entity_id: "input_select.house_mode"
          state: "Away"
    - service: notify.slack
      data:
        message: |
              Midnight. Turning off outdoor lights.

################################################################################
# Work                                                                         #
################################################################################
- alias: Set Working Scene according to binary sensor
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.joris_working
  action:
      - service: scene.turn_on
        data_template:
          entity_id: "{% raw %}{{ 'scene.Working' if is_state('binary_sensor.joris_working', 'on') else 'scene.NotWorking'}}{% endraw %}"

################################################################################
# Washing Machine/Dryer                                                        #
################################################################################

- alias: Send notification on Washing Machine done
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine
      to: 'off'
  action:
    - service: notify.slack
      data:
        message: |
              Washing machine done!

- alias: Send notification on Dryer done
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer
      to: 'off'
  action:
    - service: notify.slack
      data:
        message: |
              Dryer done!


################################################################################
# Camera                                                                       #
################################################################################

- alias: Camera Preset Home Automation
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.camera_preset
    to: "Home"
  action:
    - service: camera.turn_off
      data:
        entity_id: camera.diepvries
    - service: camera.turn_off
      data:
        entity_id: camera.office
    - service: camera.turn_on
      data:
        entity_id: camera.hallway
    - service: camera.turn_on
      data:
        entity_id: camera.front_garden
    - service: camera.turn_on
      data:
        entity_id: camera.backyard

- alias: Camera Preset All On Automation
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.camera_preset
    to: "All On"
  action:
    - service: camera.turn_on
      data:
        entity_id: camera.diepvries
    - service: camera.turn_on
      data:
        entity_id: camera.office
    - service: camera.turn_on
      data:
        entity_id: camera.hallway
    - service: camera.turn_on
      data:
        entity_id: camera.front_garden
    - service: camera.turn_on
      data:
        entity_id: camera.backyard
    - service: notify.slack
      data:
        message: |
            The place is locked down.
