################################################################################
# Bathroom                                                                     #
################################################################################

- alias: Play bathroom sonos preset for music input select
  initial_state: True
  trigger:
    platform: state
    entity_id: input_select.bathroom_music
  action:
    - service: shell_command.play_sonos_preset
      data_template:
        preset: "{% raw %}{{ states('input_select.bathroom_music') | lower | replace(' ', '_')}}{% endraw %}"

- alias: Bathroom - Set InputSelect to NoMusic when music is paused
  initial_state: True
  trigger:
    - platform: state
      entity_id: media_player.bathroom
      to: "paused"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bathroom_music
        option: "Bathroom NoMusic"

- alias: Bathroom Auto Enter - Daytime
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      to: "on"
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: 'Home'
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.BathroomEnter"

- alias: Bathroom Enter - Evening
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.bathroom_group
      to: "on"
  condition:
    - condition: sun
      after: "sunset"
      before_offset: "00:45:00"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.BathroomEnterEvening"
    - service: notify.slack
      data:
        message: |
              Bathroom Enter Evening

- alias: Bathroom Enter - Day
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.bathroom_group
      to: "on"
  condition:
    - condition: sun
      before: "sunset"
      before_offset: "01:00:00"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.BathroomEnterDay"
    - service: notify.slack
      data:
        message: |
              Bathroom Enter Day

- alias: Bathroom Exit
  initial_state: True
  trigger:
    - platform: state
      entity_id: media_player.bathroom
      from: "playing"
      to: "paused"
    - platform: state
      entity_id: light.bathroom_group
      to: "off"
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.BathroomLeave"

- alias: Music on afternoon shower during weekday
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.bathroom_group
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: "binary_sensor.housekeeping"
          state: "off"
        - condition: time
          after: '12:00:00'
          before: '17:00:00'
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
  action:
    - service: scene.turn_on
      data:
        entity_id: "scene.RelaxingShower"
