################################################################################
# Hallway Mode                                                                 #
################################################################################
- alias: Hallway evening
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.hallway
      to: "on"
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "{% raw %}scene.Hallway{{ states('input_select.house_mode')}}{% endraw %}"