prometheus_dir: /opt/prometheus
prometheus_user: prometheus
prometheus_group: "{{prometheus_user}}"

prometheus_docker_network_name: "prometheus-network"
prometheus_docker_network_subnet: "10.0.1.0/24"

prometheus_port_internal: 9090
prometheus_port_external: 9090
prometheus_docker_image: "prom/prometheus:v2.4.3"
prometheus_docker_network_ip_address: "10.0.1.2" # Note: 10.0.1.1 is taken by docker network router

node_exporter_docker_image: "prom/node-exporter:v0.16.0"
node_exporter_port_internal: 9100
node_exporter_port_external: 9100
node_exporter_docker_network_ip_address: "10.0.1.3"

blackbox_exporter_docker_image: "prom/blackbox-exporter:v0.12.0"
blackbox_exporter_port_internal: 9115
blackbox_exporter_port_external: 9115
blackbox_exporter_docker_network_ip_address: "10.0.1.4"
