prometheus_dir: /opt/prometheus
prometheus_user: prometheus
prometheus_group: "{{prometheus_user}}"

prometheus_docker_image: "prom/prometheus:v2.4.3"
prometheus_port: 9090
prometheus_host: "{{casa_ip}}"

alertmanager_docker_image: "prom/alertmanager:v0.15.2"
alertmanager_port: 9093
alertmanager_host: "{{casa_ip}}"

blackbox_exporter_docker_image: "prom/blackbox-exporter:v0.12.0"
blackbox_exporter_port: 9115
blackbox_exporter_host: "{{casa_ip}}"

node_exporter_service: "{{prometheus_user}}@prometheus-node-exporter"
node_exporter_port: 9100
node_exporter_host: "{{casa_ip}}"

node_exporter_textfile_exports: "{{prometheus_dir}}/textfile_exports"

recreate_containers: no
